### PR TITLE
Organize and clean up the /board documents

### PR DESCRIPTION
**Pull request by Jake-Gillberg**
https://github.com/rchain/bounties/issues/448

Problems:
 - Text cutoff of filenames in the github viewer makes it hard to know what each document contains.
 - Changes between versions of the bylaws are hard to see.
 - There is no file structure hierarchy, which will probably be un-maintainable in the long run.
 - All files are unsearchable PDFs

Solutions:
 - All files put in a maintainable directory structure that allows the file to be named according to it's content without having to contain date information.
 - Translated the bylaws pdf to markdown, and put it at the top level to be modified.
 - Unzipped some zip files that contained docx's and translated them to pdfs, so they are viewable in a web browser.

### CODE REVIEW

**Comment by dckc** [comment]
This is great stuff, @Jake-Gillberg !

Of course, it's only sustainable if the board agrees to this style of documentation.

@kennyrowe and @n10n made the most recent commits. What do you guys think?

@evanjensen is the coop secretary, according to the [management team section of the coop homepage](https://www.rchain.coop/#officers-management-team). Thoughts, Evan?

**Comment by Jake-Gillberg** [comment]
As per our meeting, @ian-bloom is taking responsibility for reviewing and merging.

**Review by ian-bloom — CHANGES_REQUESTED** [review]
Pls cite authoritative version:
> The following markdown was derived from this (authoritative) original doc (link)

Sorry if this was already done and I missed it. My intent here is to avoid any misunderstanding, should there be a transcription error or versioning problem.

**Review by ian-bloom — APPROVED** [review]

**Comment by ian-bloom** [comment]
style: reorganize and convert pdf to markdown [#488](https://github.com/rchain/bounties/issues/448)

**Pull request merged**
